<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>GleapSDK</RootNamespace>
    <AssemblyName>Gleap.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Gleap.Core.Tests" />
  </ItemGroup>

</Project>
