<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>GleapSDK.Sample.Wpf</RootNamespace>
    <AssemblyName>Gleap.Sample.Wpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Gleap.WebView2\Gleap.WebView2.csproj" />
    <ProjectReference Include="..\..\src\Gleap.Extensions.Logging\Gleap.Extensions.Logging.csproj" />
  </ItemGroup>

</Project>
